"""PDF report generator using fpdf2."""

from __future__ import annotations

import unicodedata
from datetime import datetime
from pathlib import Path


def _safe(text: str) -> str:
    """Replace non-latin-1 characters with ASCII equivalents or '?'."""
    # Normalize to decomposed form, then re-compose where possible
    text = unicodedata.normalize("NFKD", text)
    # Common Unicode replacements
    replacements = {
        "\u2018": "'", "\u2019": "'",  # left/right single quotes
        "\u201c": '"', "\u201d": '"',  # left/right double quotes
        "\u2013": "-", "\u2014": "-",  # en/em dash
        "\u2026": "...",               # ellipsis
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="replace").decode("latin-1")

from pycve.models.cve import CVERecord
from pycve.utils.exceptions import MissingDependencyError

# Severity → RGB colour tuples
_SEVERITY_COLORS = {
    "CRITICAL": (220, 53, 69),
    "HIGH":     (253, 126, 20),
    "MEDIUM":   (255, 193, 7),
    "LOW":      (25, 135, 84),
    "UNKNOWN":  (108, 117, 125),
}


def generate_pdf_report(cves: list[CVERecord], output_path: str | Path) -> str:
    """Generate a PDF report using fpdf2.

    Returns the absolute path of the created file.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise MissingDependencyError("fpdf2", "PDF reports", "reports")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 10, "PyCVE Security Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(
        0, 6,
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  |  Total CVEs: {len(cves)}",
        ln=True, align="C",
    )
    pdf.ln(6)

    # ── Severity summary ─────────────────────────────────────────────────
    from collections import Counter
    dist = Counter(cve.severity for cve in cves)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Severity Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for sev, count in sorted(dist.items()):
        r, g, b = _SEVERITY_COLORS.get(sev, (100, 100, 100))
        pdf.set_text_color(r, g, b)
        pdf.cell(40, 7, f"  {sev}:", ln=False)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, str(count), ln=True)
    pdf.ln(4)

    # ── CVE table header ─────────────────────────────────────────────────
    col_widths = [38, 22, 14, 24, 30, 62]
    headers = ["CVE ID", "Severity", "Score", "Published", "Status", "Description"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(26, 29, 38)
    pdf.set_text_color(226, 232, 240)
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()

    # ── CVE rows ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 7.5)
    line_h = 5  # line height per wrapped line
    left_margin = pdf.l_margin
    # Pre-compute x offsets for each column
    col_x = [left_margin + sum(col_widths[:i]) for i in range(len(col_widths))]

    for cve in cves:
        r, g, b = _SEVERITY_COLORS.get(cve.severity, (100, 100, 100))
        row_data = [
            _safe(cve.id),
            _safe(cve.severity),
            _safe(str(cve.cvss_score) if cve.cvss_score is not None else "-"),
            _safe(cve.published.strftime("%Y-%m-%d") if cve.published else "-"),
            _safe(cve.vuln_status[:20]),
        ]
        desc = _safe(cve.description)

        y0 = pdf.get_y()

        # Draw the first 5 columns using cell() at their x positions
        for i, (w, val) in enumerate(zip(col_widths[:-1], row_data)):
            pdf.set_xy(col_x[i], y0)
            pdf.set_text_color(r, g, b) if i == 1 else pdf.set_text_color(30, 30, 30)
            pdf.cell(w, line_h, val, border=1)

        # Draw description with multi_cell so text wraps inside the column
        pdf.set_text_color(30, 30, 30)
        pdf.set_xy(col_x[-1], y0)
        pdf.multi_cell(col_widths[-1], line_h, desc, border=1)

        new_y = pdf.get_y()
        row_h = new_y - y0

        # If description wrapped, extend borders for the first 5 cells
        if row_h > line_h:
            for i, w in enumerate(col_widths[:-1]):
                pdf.rect(col_x[i], y0, w, row_h)

        pdf.set_xy(left_margin, new_y)

    # ── Footer ────────────────────────────────────────────────────────────
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "Generated by PyCVE  |  Data source: NIST NVD API v2", align="C")

    pdf.output(str(output_path))
    return str(output_path.resolve())
