"""PDF report generator using fpdf2."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from pycve.models.cve import CVERecord
from pycve.utils.exceptions import MissingDependencyError

# Severity → RGB colour tuples
_SEVERITY_COLORS = {
    "CRITICAL": (220, 53, 69),
    "HIGH":     (253, 126, 20),
    "MEDIUM":   (255, 193, 7),
    "LOW":      (25, 135, 84),
    "UNKNOWN":  (108, 117, 125),
}


def generate_pdf_report(cves: list[CVERecord], output_path: str | Path) -> str:
    """Generate a PDF report using fpdf2.

    Returns the absolute path of the created file.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise MissingDependencyError("fpdf2", "PDF reports", "reports")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 10, "PyCVE Security Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(
        0, 6,
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  |  Total CVEs: {len(cves)}",
        ln=True, align="C",
    )
    pdf.ln(6)

    # ── Severity summary ─────────────────────────────────────────────────
    from collections import Counter
    dist = Counter(cve.severity for cve in cves)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Severity Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for sev, count in sorted(dist.items()):
        r, g, b = _SEVERITY_COLORS.get(sev, (100, 100, 100))
        pdf.set_text_color(r, g, b)
        pdf.cell(40, 7, f"  {sev}:", ln=False)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, str(count), ln=True)
    pdf.ln(4)

    # ── CVE table header ─────────────────────────────────────────────────
    col_widths = [38, 22, 14, 24, 30, 62]
    headers = ["CVE ID", "Severity", "Score", "Published", "Status", "Description"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(26, 29, 38)
    pdf.set_text_color(226, 232, 240)
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()

    # ── CVE rows ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 7.5)
    for cve in cves:
        r, g, b = _SEVERITY_COLORS.get(cve.severity, (100, 100, 100))
        row_data = [
            cve.id,
            cve.severity,
            str(cve.cvss_score) if cve.cvss_score is not None else "—",
            cve.published.strftime("%Y-%m-%d") if cve.published else "—",
            cve.vuln_status[:20],
            (cve.description[:80] + "…") if len(cve.description) > 80 else cve.description,
        ]

        for i, (w, val) in enumerate(zip(col_widths, row_data)):
            if i == 1:
                pdf.set_text_color(r, g, b)
            else:
                pdf.set_text_color(30, 30, 30)
            pdf.cell(w, 7, val, border=1)
        pdf.ln()

    # ── Footer ────────────────────────────────────────────────────────────
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "Generated by PyCVE  |  Data source: NIST NVD API v2", align="C")

    pdf.output(str(output_path))
    return str(output_path.resolve())
